### ISSUE TITLE
Doesn't support jhipster 7.1.0 to 7.7.0

### ISSUE THREAD

**Issue by naris** [tailosoft/jhipster-primeng-blueprint#37]
The current version of jhipster is 7.1.0 Using that produces this error:

>jhipster --blueprints primeng-blueprint
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-primeng-blueprint at npm/node_modules/generator-jhipster-primeng-blueprint
INFO! No custom commands found within blueprint: generator-jhipster-primeng-blueprint at npm/node_modules/generator-jhipster-primeng-blueprint

Welcome to JHipster v7.1.0

ERROR! The installed generator-jhipster-primeng-blueprint blueprint targets JHipster v7.0.1 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
Error: The installed generator-jhipster-primeng-blueprint blueprint targets JHipster v7.0.1 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
    at JHipsterAppGenerator.error (npm\node_modules\generator-jhipster\generators\generator-base.js:1788:11)
    at JHipsterAppGenerator._checkJHipsterBlueprintVersion (npm\node_modules\generator-jhipster\generators\generator-base-blueprint.js:424:14)
    at npm\node_modules\generator-jhipster\generators\app\index.js:314:18
    at Array.forEach (<anonymous>)
    at JHipsterAppGenerator.validateBlueprint (npm\node_modules\generator-jhipster\generators\app\index.js:313:42)
    at Object.<anonymous> (npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1024:25)
    at npm\node_modules\generator-jhipster\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at npm\node_modules\generator-jhipster\node_modules\run-async\index.js:26:19
    at runLoop.add.once.once (npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1025:11)

**Comment by yelhouti** [comment]
Things to copy from the main generator:
1. New types: with Pick Omit...
2. test-samples
3. FormService
Things to fix:
1. Use AftervIewInit to work on navigation
2. Remove the not required Date fields from updateForm

This should be released in few days.

**Comment by yelhouti** [comment]
upgraded to support latest jhipster, specifically version: https://github.com/jhipster/generator-jhipster/pull/19849

**Comment by naris** [comment]
This still has an issue
[https://github.com/tailosoft/jhipster-primeng-blueprint/issues/58](https://github.com/tailosoft/jhipster-primeng-blueprint/issues/58)
