### ISSUE TITLE
Update to Angular/PrimeNG 12/13/14

### ISSUE THREAD

**Issue by naris** [tailosoft/jhipster-primeng-blueprint#48]
Currently this blueprint only supports Angular & PrimeNG 11. They should be updated at least 12, but really 13.

**Comment by yelhouti** [comment]
upgraded to support latest jhipster, specifically version: https://github.com/jhipster/generator-jhipster/pull/19849

**Comment by naris** [comment]
The update has an issue :(
[https://github.com/tailosoft/jhipster-primeng-blueprint/issues/58](https://github.com/tailosoft/jhipster-primeng-blueprint/issues/58)

**Comment by naris** [comment]
> upgraded to support latest jhipster, specifically version: [jhipster/generator-jhipster#19849](https://github.com/jhipster/generator-jhipster/pull/19849)

That is NOT the latest jhipster. The latest jhipster is [https://www.jhipster.tech/2022/09/02/jhipster-release-7.9.3.html](https://www.jhipster.tech/2022/09/02/jhipster-release-7.9.3.html), not some branch.

That is not an acceptable solution!

**Comment by yelhouti** [comment]
@naris, there are to many changes between 7.9.3 and the main branch, and I wasn't willing to redo all the work in few weeks.
We need to convince jhipster to merge composite so we don't have to maintain it. until then this is the only possible solution.

**Comment by naris** [comment]
> @naris, there are to many changes between 7.9.3 and the main branch, and I wasn't willing to redo all the work in few weeks. We need to convince jhipster to merge composite so we don't have to maintain it. until then this is the only possible solution.

Then you should resolve the conflicts in https://github.com/jhipster/generator-jhipster/pull/19849

**Comment by yelhouti** [comment]
Feel free to help do that, I already did and new ones appeared

**Comment by naris** [comment]
I am sorry, I should not have complained and instead looked to see if I can fix it.
You indeed don't *have* to do anything and I thank you for your open source contribution.
